#%RAML 1.0 NamedExample
value:

  -
    ID: 1
    name: joseph
    accounttype: personal
    address: 12345 GreenSt,Boulder,Colorado,82433,USA
    airmiles: 20
    creationDate: 2024-01-18T12:34:56Z
  -
    ID: 2
    name: arun
    accounttype: business
    address: 12 G,Boulder,Canada,
    airmiles: 40
    creationDate: 2024-01-18T12:34:56Z
    